In [1]:
import numpy as np

In [2]:
#declaration
a = np.array([[5,5,3,50],[1,1,-1,20],[7,6,-9,30],[5,5,5,35],[2,4,-15,10],[12,10,0,90],[0,1,-10,20],[5,6,3,0]])
b = np.array([[-1,1,2],[2,3,5],[-5,2,0]])
c = np.array([[6,-3,1,2],[3,4,1,5],[6,3,0,0]])
d = np.array([[5,-7,3,50],[10,4,5,0]])

In [3]:
#coeffecient matrix/tableau for primal (weights are xn)
display(a)
display(b)
display(c)
display(d)

array([[  5,   5,   3,  50],
       [  1,   1,  -1,  20],
       [  7,   6,  -9,  30],
       [  5,   5,   5,  35],
       [  2,   4, -15,  10],
       [ 12,  10,   0,  90],
       [  0,   1, -10,  20],
       [  5,   6,   3,   0]])

array([[-1,  1,  2],
       [ 2,  3,  5],
       [-5,  2,  0]])

array([[ 6, -3,  1,  2],
       [ 3,  4,  1,  5],
       [ 6,  3,  0,  0]])

array([[ 5, -7,  3, 50],
       [10,  4,  5,  0]])

In [4]:
#coeffecient matrix/tableau for dual (weights change from xn to yn)
display(a.T)
display(b.T)
display(c.T)
display(d.T)

array([[  5,   1,   7,   5,   2,  12,   0,   5],
       [  5,   1,   6,   5,   4,  10,   1,   6],
       [  3,  -1,  -9,   5, -15,   0, -10,   3],
       [ 50,  20,  30,  35,  10,  90,  20,   0]])

array([[-1,  2, -5],
       [ 1,  3,  2],
       [ 2,  5,  0]])

array([[ 6,  3,  6],
       [-3,  4,  3],
       [ 1,  1,  0],
       [ 2,  5,  0]])

array([[ 5, 10],
       [-7,  4],
       [ 3,  5],
       [50,  0]])