In [1]:
import numpy as np

In [2]:
onea = np.array([[3,-1,2,7],[-2,4,0,12],[-4,3,8,10],[-1,3,-2,0]]).T
#x=b1;y=b2; two = np.array([[1,-5,-6,x],[1,5,2,y],[5,2,3,0]]).T
four1 = np.array([[-2,2,0,1,3],[-2,1,1,0,2],[30,-10,0,0,0]])
four2 = np.array([[-1,0,1,-.5,0.5],[-1,1,0,0.5,1.5],[20,0,0,5,15]])
six1 = np.matrix([[0.5,-.25,0],[0,0.5,0],[-2,1,1]])
six2 = np.matrix([[430],[480],[400]])

In [3]:
print('1. a) (Z is the last row)')
display(onea)
print('1. b)')
print()
print('The resource to change would be the RHS of the third constraints, as the surplus x6 has value and is in the basis. ')
print()
print('1. c)')
print()
print('This constraint can be decreased by 11 before affecting feasibility.')


1. a) (Z is the last row)


array([[ 3, -2, -4, -1],
       [-1,  4,  3,  3],
       [ 2,  0,  8, -2],
       [ 7, 12, 10,  0]])

1. b)

The resource to change would be the RHS of the third constraints, as the surplus x6 has value and is in the basis. 

1. c)

This constraint can be decreased by 11 before affecting feasibility.


In [4]:
print('3. ')
print()
print('Solving with AMPL, the number of jackets should be 144, the number of bags should be 24, and the objective function should be $53,280.')

3. 

Solving with AMPL, the number of jackets should be 144, the number of bags should be 24, and the objective function should be $53,280.


In [5]:
print('4. ')
print()
print('From solver:')
print()
print('Iteration 1')
print()
display(four1)
print()
print('Iteration 2')
print()
display(four2)
 

4. 

From solver:

Iteration 1



array([[ -2,   2,   0,   1,   3],
       [ -2,   1,   1,   0,   2],
       [ 30, -10,   0,   0,   0]])


Iteration 2



array([[ -1. ,   0. ,   1. ,  -0.5,   0.5],
       [ -1. ,   1. ,   0. ,   0.5,   1.5],
       [ 20. ,   0. ,   0. ,   5. ,  15. ]])

In [6]:
print('5. ')
print()
print('After solving, a negative dual solution indicated that it is unbounded, which means the primal is infeasible.')

5. 

After solving, a negative dual solution indicated that it is unbounded, which means the primal is infeasible.


In [7]:
print('6. ')
print()
print('When the excess is assigned to process 2 instead of 1 we multiply the following:')
display(six1)
display(six2)
print('This solution is feasible, and yields a higher objective function value (765 vs 760), but maintains an excess of 20 in x6: ')
display(six1*six2)

6. 

When the excess is assigned to process 2 instead of 1 we multiply the following:


matrix([[ 0.5 , -0.25,  0.  ],
        [ 0.  ,  0.5 ,  0.  ],
        [-2.  ,  1.  ,  1.  ]])

matrix([[430],
        [480],
        [400]])

This solution is feasible, and yields a higher objective function value (765 vs 760), but maintains an excess of 20 in x6: 


matrix([[  95.],
        [ 240.],
        [  20.]])